import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/components/Home/Navbar/ResponsiveNav";

const font = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kurt Luis Landoy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${font.className} h-full antialiased bg-[#5a213e] text-white bg-fixed`}
    >
      <body className="min-h-full flex flex-col">
        <section className="bg-gradient-to-b from-[#0d0d1f] to-[#5a213e]">
          <ResponsiveNav />
        </section>
        {children}
      </body>
    </html>
  );
}
